### ISSUE TITLE
Segfault in CopyRectangle

### ISSUE THREAD

**Issue by spaceone** [LibVNC/libvncserver#147]
Maybe you have a clue about this segfault? I don't know whether it's a bug in libvncserver or in italc:

```
Core was generated by `/usr/bin/python2.7 /usr/sbin/univention-management-console-module -m computerro'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa674b76f6b in raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:42
42      ../nptl/sysdeps/unix/sysv/linux/pt-raise.c: No such file or directory.
#0  0x00007fa674b76f6b in raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:42
#1  <signal handler called>
#2  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1090
#3  0x00007fa64ea1d017 in CopyRectangle (client=0x2e31470, buffer=0x2e56ce8 "#w", x=<optimized out>, y=16384, w=276163808, h=1946543431) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/ica/x11/libvncclient/rfbproto.c:177
#4  0x00007fa64e9eecba in DecompressJpegRect32 (client=0x2e31470, x=0, y=895, w=1920, h=<optimized out>) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/ica/x11/libvncclient/tight.c:578
#5  0x00007fa64e9ef7e8 in HandleTight32 (client=0x2e31470, rx=0, ry=895, rw=1920, rh=34) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/ica/x11/libvncclient/tight.c:124
#6  0x00007fa64ea25c62 in HandleCoRRE32 (rh=<optimized out>, rw=<optimized out>, ry=59792, rx=59776, client=0x2e31470) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/ica/x11/libvncclient/corre.c:56
#7  HandleRFBServerMessage (client=0x2e31470) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/ica/x11/libvncclient/rfbproto.c:2056
#8  0x00007fa64ea043e6 in ItalcVncConnection::doConnection (this=0x7fa64821e930) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:634
#9  0x00007fa64ea04628 in ItalcVncConnection::run (this=0x7fa64821e930) at /var/build/temp/tmp.4cEG8hN4Vz/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:517
#10 0x00007fa6718dfd0b in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x00007fa674b6eb50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#12 0x00007fa67401830d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#13 0x0000000000000000 in ?? ()
```

**Comment by bk138** [comment]
Well... That looks like... a segv in LibVNCServer!

The backtrace shows that width and height are unusually big (which could be an issue in italc) but nonetheless, that shouldn't happen.

I'll have a look.

**Comment by spaceone** [comment]
Thank you very mich :)

**Comment by bk138** [comment]
Have you tried with latest master? There were some changes and line 177 is not in CopyRectangle anymore...

**Comment by spaceone** [comment]
Thanks, I will see if this commit fixes it :)
